version: '3.7'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/app/
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8001:8000
    depends_on:
      - fuzzy_db
      - redis_server

  fuzzy_db:
    image: postgres:12.1-alpine
    volumes:
      - postgress_fuzzy:/var/lib/postgresql/data/
    env_file:
      - .env

  fuzzy_pgadmin:
    container_name: fuzzy_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - fuzzy_db
    volumes:
      - pgadmin:/root/.pgadmin

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  worker:
    build:
      dockerfile: Dockerfile
      context: backend/app/api/celery
    env_file:
      - .env
    depends_on:
      - redis_server

  dashboard:
    image: mher/flower
    command: [ "flower", "--broker=redis://redis_server:6379", "--port=5555" ]
    ports:
      - "5555:5555"
    depends_on:
      - redis_server

  redis_server:
    image: redis


volumes:
  postgress_fuzzy:
  pgadmin:


