version: '3.7'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/app/
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8001:8000
    depends_on:
      - fuzzy_db

  fuzzy_db:
    image: postgres:12.1-alpine
    volumes:
      - postgress_fuzzy:/var/lib/postgresql/data/
    env_file:
      - .env

  fuzzy_pgadmin:
    container_name: fuzzy_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - fuzzy_db
    volumes:
      - pgadmin:/root/.pgadmin

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgress_fuzzy:
  pgadmin:


